<?php

$file_name = "M_index.php";
$class = "M_index";

$module_name =  $_POST['module'];
$module_name_no_space = preg_replace('/\s+/', '', $module_name);

$moduleDir = $this->moduleDir;

$string = "<?php defined('BASEPATH') OR exit('No direct script access allowed');

class " . $class . " extends CI_Model
{
    public function __construct()
	{
		parent::__construct();
		\$this->load->database();
	}
}

";

$string .= "\n\n\n\n/* End of file $file_name */
/* Location: ./application/modules/$module_name_no_space/models/$file_name */
/* Please DO NOT modify this information : */
/* Generated by IndonesiaIT Codeigniter CRUD Generator ".date('Y-m-d H:i:s')." */
/* indonesiait.com */";


$this->createDir($moduleDir."/models/");
$result = $this->createFile($string, $moduleDir."/models/" . $file_name);

?>