<?php defined('BASEPATH') OR exit('No direct script access allowed');

class M_index extends CI_Model
{
    public function __construct()
	{
		parent::__construct();
		$this->load->database();
	}
}





/* End of file M_index.php */
/* Location: ./application/modules/download/models/M_index.php */
/* Please DO NOT modify this information : */
/* Generated by WD Codeigniter CRUD Generator 2016-11-19 05:50:58 */
/* indonesiait.com */