<?php defined('BASEPATH') OR exit('No direct script access allowed');

class M_index extends MY_backend
{
    public function __construct()
	{
		parent::__construct();
		$this->load->database();
	}
}





/* End of file M_index.php */
/* Location: ./application/modules/gallery/models/M_index.php */
/* Please DO NOT modify this information : */
/* Generated by WD Codeigniter CRUD Generator 2016-08-09 05:55:51 */
/* indonesiait.com */