<?php defined('BASEPATH') OR exit('No direct script access allowed');

class Link extends MY_backend
{
    function __construct()
    {
        parent::__construct();

		
        //library breadcrum/untuk navigasi
		$this->load->library('breadcrumb');
		$this->load->library('urlcrypt');
		
		//breadcrumb untuk navigasi
		$this->breadcrumb->add_crumb('Home');
		$this->breadcrumb->add_crumb('Link');
		
		$this->data['primary_title'] = '<i class="fa fa fa-gear"></i> Link';
		$this->data['sub_primary_title'] = '';
		
		$this->data['sub_title'] = 'Link';
		$this->layout->set_title($this->data['sub_title']);
		
		$this->table_link = 'link'; 
			
		$this->validation_rule();
    }
	
	// {VIEW} //
	function index(){
		$this->rule->type('R');
	
		$this->layout->set_include_group('index');
		$this->layout->set_include('inline',getview('index_js',$this->data));
		$this->layout->theme('backend','index', $this->data);	
	}
	
	function show(){
		$this->rule->type('R');
		$id = $this->urlcrypt->decode($this->input->get('id'));
		
		$this->layout->set_include_group('form');
		$this->layout->set_include('inline',getview('form_js'));

		$this->data['list'] = $this->wd_db->get_data_row($this->table_link,array('id'=>$id));
		
		$this->layout->theme('backend','show', $this->data);
	}
	
	// {VALIDATION RULE} //
	public function validation_rule(){
		$this->data['rules'] = array(
			array('field'   => 'title','label'   => 'Title','rules'   => 'required'),
			array('field'   => 'href','label'   => 'Href','rules'   => 'required'),
			array('field'   => 'status','label'   => 'Status','rules'   => 'required')
		);
		$this->data['rules_message'] = array();
	}
	
	function add(){
		$this->rule->type('C');
		
		//Run validate with js
		$this->wd_validation->run_validate_js($this->data['rules'],$this->data['rules_message'],'#dt_form','.validate-js-message');

		$this->layout->set_include_group('form');
		$this->layout->set_include('inline',getview('form_js'));
		$this->layout->theme('backend','add', $this->data);	
	}
	
	function edit(){
		$this->rule->type('U');
		
		$this->wd_validation->run_validate_js($this->data['rules'],$this->data['rules_message'],'#dt_form','.validate-js-message');
		
		$this->load->library('urlcrypt');
		$id = $this->urlcrypt->decode($this->input->get('id'));
		
		$this->layout->set_include_group('form');
		$this->layout->set_include('inline',getview('form_js')); 

		$this->data['list'] = $this->wd_db->get_data_row($this->table_link,array('id'=>$id));
		
		$this->layout->theme('backend','edit', $this->data);	
	}
	
	// {ACTION} //
	function save_action(){
		$this->rule->type('C');
		
		if($this->ci_validation()==FALSE)
			redirect(admin_dir().this_module().'/add');

		$data = array(
			'title' => $this->input->post('title'),
			'href' => $this->input->post('href'),
			
			'status' => $this->input->post('status')
		);
		
		$this->wd_db->add_dml_get_id($this->table_link,$data);
		
		redirect(admin_dir().this_module().'/add');
	}
	
	function update_action(){
		$this->rule->type('U');		
		$id = $this->input->post('id');
		$id = $this->urlcrypt->decode($id);

		if($this->ci_validation()==FALSE)
			redirect(admin_dir().this_module().'/edit?id='.$this->input->post('id'));
		
		$old = $this->wd_db->get_data($this->table_link,array('id' => $id)) ;

		$data = array(
			'title' => $this->input->post('title'),
			'href' => $this->input->post('href'),
			
			'status' => $this->input->post('status')
		);

		
		
		$where = array(
			'id' => $id
		);
		
		$this->wd_db->edit_dml($this->table_link,$data,$where);
			
		redirect(admin_dir().this_module().'/edit?id='.$this->input->post('id'));	
	}
	
	function delete_action(){
		
		if($this->input->get('confirm') == null){
			$this->confirm_delete($this->table_link,'id','title');
			return;
		}
			
		$del_id = $this->session->flashdata('del_id');
		$this->wd_db->del_dml_where_in($this->table_link,'id',$del_id);
		
		redirect(admin_dir().this_module());
	}
	
	// {EXTEND FUNCTION} //
	public function dataTable() {
		$this -> load -> library('Datatable', array('model' => 'm_datatables', 'rowIdCol' => 'link.id'));
		$jsonArray = $this -> datatable -> datatableJson(array());

		$list_status[0] = array('1','Active');
		$list_status[1] = array('0','No');


		foreach ($jsonArray['data'] as $index => $json) {
			foreach ($list_status as $key => $value) {
				if ($json['link']['status']==$value[0]) {
					$jsonArray['data'][$index]['link']['status']=$value[1];
				}				
			}
		}

		$this -> output -> set_header('Pragma: no-cache');
        $this -> output -> set_header('Cache-Control: no-store, no-cache');
        $this -> output -> set_content_type('application/json') -> set_output(json_encode($jsonArray));
	}
}




/* End of file Link.php */
/* Location: ./application/modules/link/controllers/Link.php */
/* Please DO NOT modify this information : */
/* Generated by WD Codeigniter CRUD Generator 2016-09-23 10:26:16 */
/* indonesiait.com */