<?php defined('BASEPATH') OR exit('No direct script access allowed');

class Statistik extends MY_backend
{
    function __construct()
    {
        parent::__construct();

		
        //library breadcrum/untuk navigasi
		$this->load->library('breadcrumb');
		$this->load->library('urlcrypt');
		$this->load->model('m_index');
		
		//breadcrumb untuk navigasi
		$this->breadcrumb->add_crumb('Home');
		$this->breadcrumb->add_crumb('Statistik');
		
		$this->data['primary_title'] = '<i class="fa fa fa-gear"></i> Statistik';
		$this->data['sub_primary_title'] = '';
		
		$this->data['sub_title'] = 'Statistik';
		$this->layout->set_title($this->data['sub_title']);
		
		$this->table_statistik = 'statistik'; 
			
		
    }
	
	// {VIEW} //
	function index(){
		$this->data['this_day']   = number_format($this->m_index->this_day(), 0, '','.');
		$this->data['this_week']  = number_format($this->m_index->this_week(), 0, '','.');
		$this->data['this_month'] = number_format($this->m_index->this_month(), 0, '','.');
		$this->data['this_year']  = number_format($this->m_index->this_year(), 0, '','.');
		$this->data['all']        = number_format($this->m_index->all(), 0, '','.');		

		$this->layout->set_include('inline',getview('index_js',$this->data));		
		$this->layout->theme('backend','index', $this->data);	
		
	}
	
	
}




/* End of file Statistik.php */
/* Location: ./application/modules/statistik/controllers/Statistik.php */
/* Please DO NOT modify this information : */
/* Generated by WD Codeigniter CRUD Generator 2016-09-27 07:16:22 */
/* indonesiait.com */