<?php defined('BASEPATH') OR exit('No direct script access allowed');

class M_index extends CI_Model
{
    public function __construct()
	{
		parent::__construct();
		$this->load->database();
	}
	function this_day(){
		$strQuery = "select count(*) as jum from statistik WHERE date = '".date('Y-m-d')."'";
		$result = $this->db->query($strQuery);
		$result = $result->row();
		$result = $result->jum;
		return $result;
	}

	function this_week(){
		$start = strtotime(date('o-\\WW')); // {isoYear}-W{isoWeekNumber}
		$end = strtotime("+6 days 23:59:59", $start);
		$strQuery = "select count(*) as jum from statistik WHERE date >='".date('Y-m-d',$start)."' and date <='".date('Y-m-d',$end)."'";
		$result = $this->db->query($strQuery);
		$result = $result->row();
		$result = $result->jum;
		return $result;
	}

	function this_month(){
		$strQuery = "select count(*) as jum from statistik WHERE date >='".date('Y-m-d',strtotime('first day of this month'))."' and date <='".date('Y-m-d',strtotime('last day of this month'))."'";
		$result = $this->db->query($strQuery);
		$result = $result->row();
		$result = $result->jum;
		return $result;
	}

	function this_year(){
		$strQuery = "select count(*) as jum from statistik WHERE date >='".date('Y-m-d',strtotime('1st jan'))."' and date <='".date('Y-m-d',strtotime('31st dec'))."'";
		$result = $this->db->query($strQuery);
		$result = $result->row();
		$result = $result->jum;
		return $result;
	}

	function all(){
		$strQuery = "select count(*) as jum from statistik";
		$result = $this->db->query($strQuery);
		$result = $result->row();
		$result = $result->jum;
		return $result;
	}
}





/* End of file M_index.php */
/* Location: ./application/modules/statistik/models/M_index.php */
/* Please DO NOT modify this information : */
/* Generated by WD Codeigniter CRUD Generator 2016-09-27 07:16:22 */
/* indonesiait.com */