<?php defined('BASEPATH') OR exit('No direct script access allowed');

class M_datatables extends CI_Model implements DatatableModel{
    	
		/**
		 * @ return
		 * 		Expressions / Columns to append to the select created by the Datatable library
		 */
		public function appendToSelectStr() {
			//_protect_identifiers needs to be FALSE in the database.php when using custom expresions to avoid db errors.
			//CI is putting `` around the expression instead of just the column names
				return NULL;
		}
    	
		public function fromTableStr() {
			return 'wd_options wd_options';
		}
    
	    /**
	     * @return
	     *     Associative array of joins.  Return NULL or empty array  when not joining
	     */
	    public function joinArray(){
			return NULL;
	    }
	    
     /**
     * 
     *@return
     *  Static where clause to be appended to all search queries.  Return NULL or empty array
     * when not filtering by additional criteria
     */
    	public function whereClauseArray(){
    		$where = "wd_options.only_super = 0";
			foreach($this->data['user_groups'] as $row){
				if($row['id']=="1"){
					$where = NULL;
					break;
				}
			}
    		return $where;
    	}
   }





/* End of file M_datatables.php */
/* Location: ./application/modules/options/models/M_datatables.php */
/* Please DO NOT modify this information : */
/* Generated by IndonesiaIT Codeigniter CRUD Generator 2017-01-26 02:30:48 */
/* indonesiait.com */