<?php defined('BASEPATH') OR exit('No direct script access allowed');

class M_index extends CI_Model
{
    public function __construct()
	{
		parent::__construct();
		$this->load->database();
	}	
}





/* End of file M_index.php */
/* Location: ./application/modules/link/models/M_index.php */
/* Please DO NOT modify this information : */
/* Generated by WD Codeigniter CRUD Generator 2016-09-23 10:26:16 */
/* indonesiait.com */